### ISSUE TITLE
[Bug] The shift to the right in automatic correction of typos

### ISSUE THREAD

**Issue by Kristinita** [gtarawneh/languagetool-sublime#15]
### Summary

Incorrect automatic replacement typos, when my text is more than one/two line. There is a shift of one character to the right.

### Expected behavior

![Without shift to the right](http://i.imgur.com/isGCHiL.gif)

### Actual behavior

![Shift to the right](http://i.imgur.com/vsnGzC8.gif)

No console output.

### Steps to reproduce

I [run LanguageTool](https://github.com/gtarawneh/languagetool-sublime/issues/8#issuecomment-236438859) → run `command: mark_language_problem_solved {"applyFix": true}`, if I make a typo.

### Environment

**Operating system and version:**
Windows 10.0.14393
**Sublime Text:**
Build 3126

Thanks.

**Comment by gtarawneh** [comment]
@Kristinita thanks again for the feedback. I've pushed a commit just now to fix this issue, would you mind testing it and letting me know how it goes?

**Comment by Kristinita** [comment]
Thanks, this bug disappeared! But bug #12 still remained 😿 .
