### ISSUE TITLE
[Feature Request] Add «Deactivate Rule» function

### ISSUE THREAD

**Issue by Kristinita** [gtarawneh/languagetool-sublime#16]
### Request

Add `Deactivate Rule` function.

### Justification

Some rules are harmful, not helpful to me. For example, rule `Use a smart opening quote here: “`. But in code I can note use smart opening quotes.

### Extended behavior

If I see rule, which is harmful for me I press <kbd>Ctrl+Shift+P</kbd> → `LanguageTool: Deactivate Rule`. Message with this rule will never bother me, including during the next sessions LanguageTool or Sublime Text. If I ever want to re-activate the rule, I must be press <kbd>Сtrl+Shift+P</kbd> → `LanguageTool: Activate Rule` → I select deactivate rule → rule is activated again.

### Example on other apps

LanguageTool Standalone have this function.

![Deactivate Rule](http://i.imgur.com/mCFX9WT.png)

Thanks.

**Comment by Kristinita** [comment]
@gtarawneh , now LanguageTool does not work.

When I restart Sublime Text, I see in console:

```
LanguageTool in E:\Sublime Text 3\Data\Installed Packages\languagetool-sublime.sublime-package:278: SyntaxWarning: name 'problems' is used prior to global declaration
```

When I run `command: language_tool`, I see in console:

```python
key evt: control+alt+l
command: language_tool
Traceback (most recent call last):
  File "E:\Sublime Text 3\sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "LanguageTool in E:\Sublime Text 3\Data\Installed Packages\languagetool-sublime.sublime-package", line 261, in run
NameError: global name 'printProblem' is not defined
```

Thanks.

**Comment by gtarawneh** [comment]
@Kristinita  Sorry it's still work in progress. Can you please use one of earlier releases for now?

**Comment by gtarawneh** [comment]
@Kristinita I'm not getting the same error for some reason, it's working fine on my computer. I noticed that you're running the plugin in a package (i.e. in  `sublime-package` file), did you package it yourself?

**Comment by Kristinita** [comment]
Works for me. Thank you very much!

I install Language Tool use [Package Control: Add Repository](http://nbviewer.jupyter.org/github/Kristinita/SashaBooks/blob/master/IT/Sublime%20Text/Sublime%20Text%20Power%20User.pdf#page=16) and I get all changes of this package, even if this changes not released.

**Comment by gtarawneh** [comment]
You do? I thought Package Control only pulls the last release (and not the last commit)? I'll check this out but if not then I have to be careful about pushing half-baked and untested features. Thanks for letting me know.
