### ISSUE TITLE
[Feature request] Default server by default if I use local server

### ISSUE THREAD

**Issue by Kristinita** [gtarawneh/languagetool-sublime#18]
### Request

Run default server by default even if in my settings my local server.
### Justification
1. I don't need often use localhost, usually default server enough for me.
2. Local server consumes > 280 Mb in RAM. It's a lot. I don't want, that local server was enabled always.

I can change server in my settings, but if I need check long text, I need change settings again. It would be nice if users can change server without manually change settings file.
### Extended behavior

My `User\LanguageTool.sublime-settings` file:

``` json
{
    "display_mode": "panel",
    "languagetool_jar": "E:/Chocolatey/lib/languagetool/tools/LanguageTool-3.5/languagetool.jar",
    "languagetool_server": "http://localhost:8081/v2/check"
}

```

If <kbd>Ctrl+Shift+P</kbd> → `LanguageTool: Check Text` → Language Tool default server run even if other server in my settings.

If <kbd>Ctrl+Shift+P</kbd> → `LanguageTool: Start Local Server` → run my local server.

Thanks.

**Comment by gtarawneh** [comment]
@Kristinita I added the following commands to the palette:

```
LanguageTool: Check Text (Local Server)
LanguageTool: Check Text (Remote Server)
```

When using either the plugin will check text using the indicated server regardless of your default server setting. The command `LanguageTool: Check Text` is still available and will run the check using the _default_ server (either local or remote) which is specified in the settings. Please note the settings file has been revised so you may need to reconfigure yours.
