### ISSUE TITLE
[Feature request] Disable horizontal scrollbar in LanguageTool panel

### ISSUE THREAD

**Issue by Kristinita** [gtarawneh/languagetool-sublime#19]
### Request

It would be nice, if you disable horizontal scrollbar in LanguageTool panel.

### Actual behavior

![Actual behavior](http://i.imgur.com/5O8X8XS.png)

### Justification

To read the all text in LanguageTool panel I need use horizontal scrollbar. It is uncomfortable.

### Extended behavior

![Extended behavior](http://i.imgur.com/O9bS5BS.png)

in LanguageTool panel.

Thanks.

**Comment by gtarawneh** [comment]
@Kristinita Done
