### ISSUE TITLE
[Enquiry] Starting local server in linux

### ISSUE THREAD

**Issue by lf-araujo** [gtarawneh/languagetool-sublime#21]
Dear gtarawneh,

Is the address to languagetool_jar hardcoded? I have it installed in my archlinux system and in the PATH, but I get:

`Error, could not find LanguageTool's JAR file (C:\bin\LanguageTool-3.5\languagetool.jar)`

If I try to start it. There is any way I can change that address to the proper one?

Thank you!

**Comment by gtarawneh** [comment]
@lf-araujo no that's only the default setting. You can set your own JAR path in the `languagetool_jar` setting in `Preferences.sublime-settings`. For reference, the plugin's settings are in: 

https://github.com/gtarawneh/languagetool-sublime/blob/master/LanguageTool.sublime-settings
