### ISSUE TITLE
Not easy to configure

### ISSUE THREAD

**Issue by reagle** [gtarawneh/languagetool-sublime#24]
I installed via package control, but I don't know how to configure. I can't find any preferences file. Using MAC Sierra and ST 3136.

**Comment by reagle** [comment]
I've set the following in my Preferences.sublime-settings:
```
	"languagetool_jar": "/Users/reagle/bin/LanguageTool-3.7/languagetool.jar",
```
but I still get an error:
```
Error, could not find LanguageTool's JAR file (C:\bin\LanguageTool-3.5\languagetool.jar)

Please install LT in this directory or modify the `languagetool_jar` setting.
```

**Comment by reagle** [comment]
When I ask it to use the remote server, it says "Cannot parse server response..."

**Comment by gtarawneh** [comment]
@reagle this plugin's settings must be stored in a `LanguageTool.sublime-settings` file in `Packages\User`. To get to the `Packages` directory, bring up the command pallette (`Ctrl-P` or equivalent) and type `Preferences: Browse Packages` then press Enter.

I suppose it makes more sense to have the preferences in `Preferences.sublime-settings`. I'll look into implementing that.

If you have other issues with the plugin, would you mind filing these as independent Github Issues? this will make them easier to debug and fix. Thanks!

**Comment by reagle** [comment]
`LanguageTool.sublime-settings` does not exist. Nor do I see anything in /Sublime Text/Preferences/Package Settings/

**Comment by reagle** [comment]
I created the file and include:
```
{
"languagetool_jar": "/Users/reagle/bin/LanguageTool-3.7/languagetool.jar",
"languagetool_server_local": "http://localhost:8081/v2/check",
"languagetool_server_remote": "https://languagetool.org/api/v2/check",
}
```
but I can't get it to work.

**Comment by gtarawneh** [comment]
Yes `LanguageTool.sublime-settings` does not exist by default and has to be created. Unfortunately I don't have a machine with OSX so I can't test why it's not working for you. Are you sure the packages directory is correct? According to [this SO thread](https://stackoverflow.com/questions/7808452/what-is-the-full-path-to-the-packages-folder-for-sublime-text-2-on-mac-os-lion), it's: `~/Library/Application Support/Sublime Text 3`

**Comment by reagle** [comment]
```
╰─➤  cat '/Users/reagle/Library/Application Support/Sublime Text 3/Packages/User/LanguageTool.sublime-settings'
{
"languagetool_jar": "/Users/reagle/bin/LanguageTool-3.7/languagetool.jar",
"languagetool_server_local": "http://localhost:8081/v2/check",
"languagetool_server_remote": "https://languagetool.org/api/v2/check",
}
```

**Comment by gtarawneh** [comment]
Default and user settings are now available from the `Preferences` menu
