### ISSUE TITLE
Start server is not working

### ISSUE THREAD

**Issue by reagle** [gtarawneh/languagetool-sublime#25]
Following on from issue #24 and using the following configuration:

```
╰─➤  cat '/Users/reagle/Library/Application Support/Sublime Text 3/Packages/User/LanguageTool.sublime-settings'
{
"languagetool_jar": "/Users/reagle/bin/LanguageTool-3.7/languagetool.jar",
"languagetool_server_local": "http://localhost:8081/v2/check",
"languagetool_server_remote": "https://languagetool.org/api/v2/check",
}
```
If I use the ST command `Start Local Server` I get a "could not parse server response" error when I then invoke `Check Text (Local Server)`. I can see that the server is running (though I don't know what port):

```
reagle           14478   0.0  4.7  6992972 396872   ??  S     8:17AM   0:07.14 /usr/bin/java -jar /Users/reagle/bin/LanguageTool-3.7/languagetool.jar -t
```

If I kill that process and manually run the following, then `Check Text (Local Server)` works!

```
java -cp ~/bin/LanguageTool-3.7/languagetool-server.jar org.languagetool.server.HTTPServer --port 8081
```

**Comment by automan000** [comment]
Hi. I find the same issue on my mac.
My solution is:
+ open Packages/LanguageTool/LanguageTool.py
+ change Line 200 from
```python
cmd = ['java', '-jar', jarPath, '-t']
```
to
```python
cmd = ['java', '-cp', jarPath, 'org.languagetool.server.HTTPServer', '--port', '8081']
```
+ Note that you have to modify "jarPath" in LanguageTool.sublime-settings first.

**Comment by digulla** [comment]
Same bug as #29 which has a PR.

**Comment by digulla** [comment]
This was fixed with https://github.com/gtarawneh/languagetool-sublime/pull/36 . Can it be closed?

**Comment by reagle** [comment]
I'm not using this, and if documented and fixed elsewhere, fine by me.
