### ISSUE TITLE
Variable languagetool_server_remote is never used?

### ISSUE THREAD

**Issue by n0guest** [gtarawneh/languagetool-sublime#26]
Hi.

I tried to change remote server URL by copying LanguageTool.sublime-settings (from package) as Packages/User/LanguageTool.sublime-settings. But it seems like "languagetool_server_remote" is never used, because LanguageTool.py logic of server selections:

```
        if forceServer is None:
                forceServer = settings.get('default_server', 'remote')
        if forceServer == "local":
                server = settings.get('languagetool_server_local', 'http://localhost:8081/v2/check')
        else:
                server = settings.get('languagetool_server', 'https://languagetool.org/api/v2/check')
        return server
```
And if you have value "remote" in "default_server" then code above will choose 'https://languagetool.org/api/v2/check' as server URL.

Am i missing something or it's really broken?

Thanks.

**Comment by gtarawneh** [comment]
Yeah it's incorrect; the setting in the else branch should be `languagetool_server_remote`, not `languagetool_server`. Good catch!

**Comment by n0guest** [comment]
Thanks for the fix. BTW, when it will be available via Package Control in Sublime? Do you upload it manually or automatically?

**Comment by gtarawneh** [comment]
You're welcome. I need to double check that the latest commits are stable for a release, which might take few days, but the master branch is generally stable so you can safely install from this repo directly using `Package Control: Add Repository`.
