### ISSUE TITLE
Improvments for README

### ISSUE THREAD

**Issue by paul-hammant** [gtarawneh/languagetool-sublime#27]
1. Mention of `LanguageTool.sublime-settings` has an extraneous space next to the dash that is going to confuse noobs

2. Location of `LanguageTool.sublime-settings` should be mentioned, and the fact that it does not exist by default

3. Contents of `LanguageTool.sublime-settings` should be suggested, including which keys are mandatory.

4. Notes needed for whether this plugin can launch the language tool server or not. In the not case, languagetool's own server documentation is already linked to, but this plugin's README could be even better if it explicitly called out the need to have that local server running already.

**Comment by gtarawneh** [comment]
@paul-hammant thanks for the suggestions, all very useful

**Comment by paul-hammant** [comment]
You're welcome, thanks for processing these :)
