### ISSUE TITLE
Captions and other commands with text content are ignored

### ISSUE THREAD

**Issue by CapXilinx** [gtarawneh/languagetool-sublime#34]
Hi,

the currently ignored scopes ignore too many Latex constructs, e.g. caption texts get completely ignored. Is there some manual how to fine-tune the ignored scopes?

Best regards,
Martin

**Comment by gtarawneh** [comment]
Hey Martin,

You can override the setting below to specify which scopes you'd like to ignore.

https://github.com/gtarawneh/languagetool-sublime/blob/47b35d7f8af99ffe51e314c1e01a72cc47de4ded/LanguageTool.sublime-settings#L8

Hope this is useful.

Ghaith

**Comment by CapXilinx** [comment]
Hi Ghaith,

thanks, that I already saw, what I was missing is how to get the correct scope names, which can be obtained by placing the cursor on the appropriate element and pressing Ctrl+Alt+Shift+P, if somebody is interested.

I updated my ignored-scopes setting to:
    "ignored-scopes":[
    	"comment.*.tex",
    	"support.function.*.latex",
    	"meta.preamble.usepackage.latex",
    	"meta.preamble.documentclass.latex",
    	"meta.function.citation.latex",
    	"meta.preamble.usepackage.latex",
    	"meta.function.label.latex",
    	"meta.function.reference.latex",
    	"keyword.control.tex"
    ]

which gives me an acceptable trade off between false positives and coverage.

Thanks again!
Martin
