### ISSUE TITLE
Stop LanguageTool/Remove Suggestions

### ISSUE THREAD

**Issue by adibender** [gtarawneh/languagetool-sublime#5]
Once LaguageTool is started (ctrl+shift+c) and problematic passages are highlighted, is there a way to stop LanguageTool/remove highlighting (without going through individual suggestions 1 by 1?

**Comment by gtarawneh** [comment]
Yes there is. It is listed in the command palette as `LanguageTool: Clear Problems` but doesn't have a keybinding by default.

**Comment by gtarawneh** [comment]
Sorry just realized this was coded but not released yet. I'll release it soon.

**Comment by gtarawneh** [comment]
It's out (v0.2.0).

**Comment by adibender** [comment]
Thx for the quick update!
