### ISSUE TITLE
Bilingual mode

### ISSUE THREAD

**Issue by Kristinita** [gtarawneh/languagetool-sublime#6]
Hello, at my texts there are both Russian, and English words. But LanguageTool English words are marked as wrong.

![English words](http://i.imgur.com/C4cG3v0.png)

But `Test` and `Example` it is not wrong words, it is words of the English language.

Is it possible to make the plug-in spelling in the text at the same time as the Russian and English words, without noting the words of another language in error?

Thanks.

**Comment by gtarawneh** [comment]
This doesn't appear to be supported by LanguageTool so can't do anything about it unfortunately
