### ISSUE TITLE
[Bug] Not change languages

### ISSUE THREAD

**Issue by Kristinita** [gtarawneh/languagetool-sublime#7]
### Summary

Bug to 

 ```
 {
		"caption": "LanguageTool: Change Language",
		"command": "change_language_tool_language"
	}
```

### Expected behavior

Change language

### Actual behavior

Not change language

### Steps to reproduce

It is checked on the portable Sublime Text 3 version where there are no other plugins. <kbd>Ctrl+Shift+P</kbd> → `Language Tool: Change Language`:

```
command: change_language_tool_language
Traceback (most recent call last):
  File "E:\Sublime Text 3\sublime_plugin.py", line 574, in run_
    return self.run(edit)
  File "LanguageTool in E:\Sublime Text 3\Data\Installed Packages\LanguageTool.sublime-package", line 160, in run
  File "LanguageTool in E:\Sublime Text 3\Data\Installed Packages\LanguageTool.sublime-package", line 34, in loadLanguages
FileNotFoundError: [Errno 2] No such file or directory: 'languages.txt'
```

### Environment

* Operating system and version:
  * [√] Windows 10 Education
  * [ ] Mac OS ...
  * [ ] Linux ...
* Sublime Text:
  * Build 3114

**Comment by gtarawneh** [comment]
@Kristinita would you be able to test the latest commit just to confirm the issue has been resolved? Otherwise I'll just publish a new release and you can test the fix once the release is picked up by PackageControl?

**Comment by Kristinita** [comment]
@gtarawneh , thank you! I checked, now at me language was replaced correctly.

![Fixed bug](http://i.imgur.com/25hkBAE.png)
