### ISSUE TITLE
Context and links for errors

### ISSUE THREAD

**Issue by Kristinita** [gtarawneh/languagetool-sublime#9]
When I start Standalone LanguageTool, the following information is output.

![Standalone LanguageTool](http://i.imgur.com/8GrYmdv.png)

But when I apply your plugin besides to the text, only the error message and corrections is displayed.

![Console message](http://i.imgur.com/UPyTrFz.png)

You would do well to output information to which the arrows point in the top screenshot optionally?

Thanks.

**Comment by Kristinita** [comment]
@gtarawneh, actually. When I use LanguageTool Standalone, I often turn on links in **More Info:**, because I do not know much English.

Thanks.

**Comment by gtarawneh** [comment]
@Kristinita just added, I will publish it with the next release (you can clone the repo to test it in the meanwhile if you like).

**Comment by Kristinita** [comment]
Thanks, it's work!
